apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scalable-web
  template:
    metadata:
      labels:
        app: scalable-web
    spec:
      containers:
      - name: webapp-container
        image: local-webapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: STUDENT_NAME
          value: "Feba Najim"